name: .NET verbose build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore --verbosity diagnostic
    - name: Build
      run: dotnet build --no-restore --verbosity diagnostic
    - name: Test
      run: dotnet test --verbosity diagnostic
